---
title: "Neural Crest single-cell ATAC-Seq Timecourse"
output: html_notebook
---

## Part 0: Project Description

We will try to stick to Seurat-based objects as much as possible, which have provided the most flexibility and integrations. Recent updates to Seurat have also increased interoperability with Monocle3 and other tools. 

There are a total of 3 10X sequencing runs that we have performed.
Each of them have been summarized using the cellranger-atac pipeline into their respective timepoints.

## Part 1: Recalling peaks with MACS3

Because 10X called peaks are sometimes very large and in order to increase sensitivity to rare peaks, we call peaks using MACS3 for every cluster within every timepoint. We accomplish this through the CallPeaks function in Signac.

## Part 2: ArchR Analysis

[ArchR](https://www.archrproject.com/bookdown/getting-started-with-archr.html) is a new project from the Greenleaf lab that is a new analysis package optimized for parallel computing and massive datasets. It uses space-efficient hd5 files in a single-cell format (.arrow) to store metadata and sparce matricies on disk, load them into RAM and process in chunks. We will use ArchR for dimensionality reduction, clustering, feature extraction (Differential Peaks, Motifs, and Genescores), Pseudotime, and some visualizations. Figure-level exports are kept in a separate .Rmd file.

As this is a new package there have been some issues running some functions. In particular, making .arrow files is broken in the development 1.0.2 package. However, calling doublets in 1.0.1 is broken. There are also issues with plotting Heatmaps. So, I loaded doublets using the 1.0.2 function, but used 1.0.1 for the remaining analysis.



## Part X: Visualizations

It can be really hard to keep track of what code was used to generate figures, especially with unique analysis. To this end, this will be strictly kept to reading data from the disk and visualizing it without further processing. Each figure will have a section.